Install requirements

python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
or
sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose

pip3 install scikit-learn
sudo apt-get install python3-tk


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Definindo lista de variáveis.

In [2]:
columns = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'classification']
df = pd.read_csv('../data/nursery.data.csv', header=None, names=columns)

In [3]:
df.describe()

parents     has_nurs    form children     housing finance  \
count         12960        12960   12960    12960       12960   12960   
unique            3            5       4        4           3       2   
top     pretentious  less_proper  foster     more  convenient  inconv   
freq           4320         2592    3240     3240        4320    6480   

               social    health classification  
count           12960     12960          12960  
unique              3         3              5  
top     slightly_prob  priority      not_recom  
freq             4320      4320           4320

In [4]:
df.head()

parents has_nurs      form children     housing     finance         social  \
0   usual   proper  complete        1  convenient  convenient        nonprob   
1   usual   proper  complete        1  convenient  convenient        nonprob   
2   usual   proper  complete        1  convenient  convenient        nonprob   
3   usual   proper  complete        1  convenient  convenient  slightly_prob   
4   usual   proper  complete        1  convenient  convenient  slightly_prob   

        health classification  
0  recommended      recommend  
1     priority       priority  
2    not_recom      not_recom  
3  recommended      recommend  
4     priority       priority

## Separando a variável dependente.


In [5]:
X = pd.get_dummies(df.drop('classification', axis=1))

## Atribuição da variável dependente.

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['classification'])

## Separando dados de teste e treino.

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

## Normalizando variáveis. Colocando todas em uma mesma escala para que a diferenças de grandezas não pese no resultado.

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

* Faz o agrupamento dos vizinhos com base na probabilidado do acontecimento, diferindo do knn que agrupa pelo o numero de vizinhos. 



In [11]:
print(classifier.score(X_test, y_test))

0.8387345679012346


In [12]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [13]:
print(cm)

[[1320    0    0    0    0]
 [   0  833    0  193  246]
 [   0    0    0    0    2]
 [   0  186    0 1004    0]
 [   0    0    0    0  104]]
