# Naive Bayes

Os metodos de Naive Bayes são uma coleção de algoritmos que se baseam no teorema de Baye, com a suposição "naive".

<img src="Bayes-Theorem-Formula-Defined.jpeg">




In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
columns = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'classification']
df = pd.read_csv('../data/nursery.data.csv', header=None, names=columns)

In [5]:
X = pd.get_dummies(df.drop('classification', axis=1))

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['classification'])

Separando dados de teste e treino.

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

Normalizando variáveis. Colocando todas em uma mesma escala para que a diferenças de grandezas não pese no resultado.

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Instanciando o algoritmo "Gaussian Naive Bayes". Existem outros algoritmos para o metodo Naive Bayes como "Multinomial Naive Bayes" e "Bernoulli Naive Bayes". O metodo Gaussiano é o mais indicado pela disposição dos dados.

In [9]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

Printando o score.

In [11]:
print(classifier.score(X_test, y_test))

0.8387345679012346


In [12]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[1320    0    0    0    0]
 [   0  833    0  193  246]
 [   0    0    0    0    2]
 [   0  186    0 1004    0]
 [   0    0    0    0  104]]


In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1320
          1       0.82      0.65      0.73      1272
          2       0.00      0.00      0.00         2
          3       0.84      0.84      0.84      1190
          4       0.30      1.00      0.46       104

avg / total       0.87      0.84      0.85      3888



/home/anderson/.local/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
