In [ ]:
"""
Install requirements

python -m pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
or
sudo apt-get install python-numpy python-scipy python-matplotlib ipython ipython-notebook python-pandas python-sympy python-nose

pip3 install scikit-learn
sudo apt-get install python3-tk

"""


In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
columns = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'classification']
df = pd.read_csv('../data/nursery.data.csv', header=None, names=columns)

In [3]:
X = pd.get_dummies(df.drop('classification', axis=1))

In [4]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['classification'])

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB(priors=None)

In [8]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [10]:
print(y_pred)

[0 1 1 ... 0 1 3]


In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [11]:
print(cm)

[[1320    0    0    0    0]
 [   0  833    0  193  246]
 [   0    0    0    0    2]
 [   0  186    0 1004    0]
 [   0    0    0    0  104]]
