In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
columns = ['parents', 'has_nurs', 'form', 'children', 'housing', 'finance', 'social', 'health', 'classification']
df = pd.read_csv('../data/nursery.data.csv', header=None, names=columns)

In [3]:
X = pd.get_dummies(df.drop('classification', axis=1))

In [18]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(df['classification'])

In [40]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# 1

In [23]:
from sklearn.tree import DecisionTreeClassifier

In [25]:
dtree = DecisionTreeClassifier()

In [28]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [31]:
pred = dtree.predict(X_test)

In [32]:
dtree.score(X_test, y_test)

0.9958847736625515

In [35]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [37]:
print(classification_report(y_test, pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00      1320
          1       0.99      1.00      0.99      1272
          2       0.00      0.00      0.00         2
          3       1.00      0.99      0.99      1190
          4       0.96      1.00      0.98       104

avg / total       1.00      1.00      1.00      3888



/usr/lib/python3.6/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [39]:
print(confusion_matrix(y_test, pred))

[[1320    0    0    0    0]
 [   0 1266    0    4    2]
 [   0    0    0    0    2]
 [   0    8    0 1182    0]
 [   0    0    0    0  104]]


# 2